language: cpp
compiler: 
  - g++
node_js: 
  - 6.17.1
os: linux
dist: xenial
addons:
  apt:
    packages:
      - cmake
      - protobuf-compiler
      - python-protobuf
      - doxygen
      - g++-multilib 
      - gcc-multilib
      - graphviz
script:
  - ls -la; cd tools/commander; npm install; cd ../../; make bebop2/sitl