language: cpp
compiler: 
  - g++
node_js: 
  - 6.17.1
os: linux
dist: xenial
addons:
  apt:
    packages:
      - cmake
      - protobuf-compiler
      - python-protobuf
      - doxygen
      - g++-multilib 
      - gcc-multilib
      - graphviz
      - libeigen3-dev
      - libopencv-dev
      - valgrind
      - libimage-exiftool-perl
      - catkin
      - python-jinja2
      - python-empy
      - python-pip
      - python-dev
      - build-essential
      - python-dev
      - flex
      - bison
      - libncurses5-dev
      - libimage-exiftool-perl
      - libc6-dbg 
      - libc6-dbg:i386
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libglib2.0-dev
before_install:
  - sudo -H pip install --upgrade pip 
  - sudo -H pip install --upgrade virtualenv 
  - sudo -H pip install catkin_pkg
  - sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
  - wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install -y gazebo8 libgazebo8 libgazebo8-dev
script:
  - cd tools/commander; 
  - npm install
  - cd ../../
  - make bebop2/sitl
  

  
