env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "JebOdbnvXHkjT0n/k94FrRSYL4Mwu2sFT0TtHSX5bMQRzlc0RAgbffiaHS4V/GIlZ8Bh34U+FuVddZEAl+Qn6I2YtI8j9R/o4FldByvV/rgXGosuQlTbHdTKZh2m+i9AtOVpwUGbguSqcYvVcPIPnm3GshYrlIOmLDxdfsp7nIEq2S04Yf7TC26hoDjTV6VdqoMBKkryQIQr+150wbC84NmzrQFbWhuQJ+UHr3Nf8fithSLECEMPDep0cxKpRw9fCqH3iNQ6Ic5Ul/0HMFPoa58Dz0/4lXnh3mHaen6K5OUPhmGN/hmzxDucw8/I/jRw7lyKI8wEpGvBx+oXtafwqtF+ao04TILnbI3WCDDmZvtU5wj01KxBY9qkECNTsXPJJuwiZ9DIm2mox9uvCYe2sJST9mAvGGh95oVPoqOuRRCrbs14/4+FYAeweNHHo7BFyOdCChPfTbyNAHSHYNCfOP/QNN2Wjmm9+7Y7xkGyz0FyOdaLtYAg9QyWUfo9mEq5INkquCVfA8WXBdmSu8rVFhU5+m5GgZSElZK5Smfew3Xrm/YP1VHQ2Ju+xSvyjV1GbQj8YVOONeWdJAP/l1UALeKY4i8pgd1M+P6YWisR7EstCgDgEBHFLF5RuzHJYsI+ZcEVt3uXje1IhHu0ku//UkUE4n8AN2uLRIGsC4VAsGo="

language: cpp
compiler: 
  - g++
node_js: 
  - 6.17.1
os: linux
dist: xenial
addons:
  apt:
    packages:
      - cmake
      - protobuf-compiler
      - python-protobuf
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - g++-multilib 
      - gcc-multilib
      - graphviz
      - libeigen3-dev
      - libopencv-dev
      - valgrind
      - libimage-exiftool-perl
      - catkin
      - python-jinja2
      - python-empy
      - python-pip
      - python-dev
      - build-essential
      - python-dev
      - flex
      - bison
      - libncurses5-dev
      - libimage-exiftool-perl
      - libc6-dbg 
      - libc6-dbg:i386
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libglib2.0-dev
  coverity_scan:
    project:
      name: "WindhoverLabs/airliner"
      description: "Mission critical UAS autopilot"
    notification_email: mbenson@windhoverlabs.com
    build_command_prepend: ""
    build_command: "make bebop/sitl"
    branch_pattern: integration/WINDEV-758-flight-test-12
before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - sudo -H pip install --upgrade pip 
  - sudo -H pip install --upgrade virtualenv 
  - sudo -H pip install catkin_pkg
  - sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
  - wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install -y gazebo8 libgazebo8 libgazebo8-dev
  - sudo apt-get install -y libeigen3-dev libopencv-dev
  - sudo apt-get install -y valgrind gcovr lcov xsltproc graphviz
  - cd tools/commander
  - npm install
  - cd ../../
script:
  - #make bebop2/sitl
  - #cd build/bebop2/sitl
  - #ctest -E ea-perf
after_success:
  - export GH_REPO_ORG=`echo $TRAVIS_REPO_SLUG | cut -d "/" -f 1`
  - export GH_REPO_NAME=`echo $TRAVIS_REPO_SLUG | cut -d "/" -f 2`
  - export GH_REPO_REF="github.com/$GH_REPO_ORG/$GH_REPO_NAME.git"
  - mkdir -p build/reference/default
  - cd build/reference/default
  - cmake -DBUILDNAME:STRING=reference/default
  - make docs
  - git clone -b gh-pages git@github.com:$GH_REPO_ORG/$GH_REPO_NAME.git code_docs
  - cd code_docs
  - ##### Configure git.
  - # Set the push default to simple i.e. push only the current branch.
  - git config --global push.default simple
  - # Pretend to be an user called Travis CI.
  - git config user.name "Travis CI"
  - git config user.email "travis@travis-ci.org"
  - # go back to first commit
  - git reset --hard `git rev-list --max-parents=0 --abbrev-commit HEAD`
  - # Need to create a .nojekyll file to allow filenames starting with an underscore
  - # to be seen on the gh-pages site. Therefore creating an empty .nojekyll file.
  - # Presumably this is only needed when the SHORT_NAMES option in Doxygen is set
  - # to NO, which it is by default. So creating the file just in case.
  - echo "" > .nojekyll
  - ################################################################################
  - ##### Upload the documentation to the gh-pages branch of the repository.   #####
  - cp -R ../docs/* .
  - git add --all
  - # Commit the added files with a title and description containing the Travis CI
  - # build number and the GitHub commit reference that issued this build.
  - git commit -m "Deploy code docs to GitHub Pages Travis build: ${TRAVIS_BUILD_NUMBER}" -m "Commit: ${TRAVIS_COMMIT}"
  - # Force push to the remote gh-pages branch.
  - # The ouput is redirected to /dev/null to hide any sensitive credential data
  - # that might otherwise be exposed.
  - git push --force "git@github.com:$GH_REPO_ORG/$GH_REPO_NAME.git" > /dev/null 2>&1
  
